import type { AgentForemanConfig } from "../types.js";

export const DEFAULT_CONFIG: AgentForemanConfig = {
  max_concurrent_workers: 3,
  runtime: {
    default_adapter: "claude_cli",
    enable_sdk_adapter: false,
    fallback_to_cli: true,
  },
  worker_idle_timeout_sec: 900,
  permission_rules: [
    {
      project_id: "*",
      effect: "deny",
      tool: "Bash",
      pattern: "rm -rf *",
      scope: "global",
      expires_at: null,
      created_by: "system_default",
    },
    {
      project_id: "*",
      effect: "deny",
      tool: "Bash",
      pattern: "sudo *",
      scope: "global",
      expires_at: null,
      created_by: "system_default",
    },
    {
      project_id: "*",
      effect: "deny",
      tool: "Bash",
      pattern: "curl *",
      scope: "global",
      expires_at: null,
      created_by: "system_default",
    },
    {
      project_id: "*",
      effect: "deny",
      tool: "Bash",
      pattern: "wget *",
      scope: "global",
      expires_at: null,
      created_by: "system_default",
    },
    {
      project_id: "*",
      effect: "deny",
      tool: "Read",
      pattern: "*.env*",
      scope: "global",
      expires_at: null,
      created_by: "system_default",
    },
    {
      project_id: "*",
      effect: "deny",
      tool: "Read",
      pattern: "~/.ssh/*",
      scope: "global",
      expires_at: null,
      created_by: "system_default",
    },
    {
      project_id: "*",
      effect: "ask",
      tool: "Bash",
      pattern: "npm test*",
      scope: "global",
      expires_at: null,
      created_by: "system_default",
    },
    {
      project_id: "*",
      effect: "ask",
      tool: "Bash",
      pattern: "pytest*",
      scope: "global",
      expires_at: null,
      created_by: "system_default",
    },
    {
      project_id: "*",
      effect: "ask",
      tool: "Bash",
      pattern: "uv run pytest*",
      scope: "global",
      expires_at: null,
      created_by: "system_default",
    },
  ],
};
