// ── Claude runner types (used by claude_cli_runner.ts) ──

export const FINAL_TASK_STATUSES = ["completed", "failed", "timeout", "stopped"] as const;
export type FinalTaskStatus = (typeof FINAL_TASK_STATUSES)[number];

export interface ClaudeCliRunOptions {
  projectPath: string;
  task: string;
  timeoutSec: number;
  onStdout?: (chunk: string) => void;
  onStderr?: (chunk: string) => void;
}

export interface ClaudeCliRunResult {
  status: FinalTaskStatus;
  stdout: string;
  stderr: string;
  exitCode: number | null;
  pid: number | undefined;
  startedAt: Date;
  finishedAt: Date;
  durationMs: number;
  error?: string;
}

export interface RunningClaudeCli {
  pid: number | undefined;
  finished: Promise<ClaudeCliRunResult>;
  stop: (reason?: string) => void;
}

// ── Session file (generated by wrapper) ──

export interface SessionFile {
  version: 1;
  session_id: string;
  project_path: string;
  supervisor_home: string;
  task_dir: string;
  artifact_root: string;
  claude_env_file: string;
  created_at: string;
}

// ── Parsed TaskFile ──

export const WORKER_TYPES = ["readonly", "write"] as const;
export type WorkerType = (typeof WORKER_TYPES)[number];

export interface ParsedTaskFile {
  task_id: string;
  worker_type: WorkerType;
  goal: string;
  allowed_scope: string;
  forbidden_actions: string;
  acceptance_criteria: string;
  verification: string;
  report_requirements: string;
}

// ── Delegate result ──

export interface DelegateResult {
  task_id: string;
  worker_type: WorkerType;
  status: FinalTaskStatus;
  exit_code: number | null;
  duration_ms: number;
  artifact_dir: string;
  changed_files: string[];
  summary: string;
  error?: string;
}
